### ISSUE TITLE
gfract doesn't work

### ISSUE THREAD

**Issue by loskiq** [floodcode/gfract#1]
##### Brief Description

OS: Debian 9 XFCE
Fract version: First release
Commit hash: b5db19569657e437f6a1c9e08400d15c24db13f9
Hardware: Intel Core i5, Nvidia GeForce GTX 1060

##### Steps to reproduce

```
loskiq@loskiq-work:~$ go gfract.go
bash: go: command not found
loskiq@loskiq-work:~$
```

**Comment by floodcode** [comment]
```
sudo apt install -y golang && go build && ./gfract
```
